### ISSUE TITLE
Reset command fails

### ISSUE THREAD

**Issue by SimplisticGH** [Vernoxvernax/Nyaa-Notifications#1]
```
thread 'tokio-runtime-worker' panicked at src/commands/reset.rs:14:7:
Discord returned invalid command options.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Could be an issue on my part, though.

**Comment by Vernoxvernax** [comment]
@SimplisticGH 
Thank you for opening this issue.
I unfortunately don't have the time to test my scripts often enough, so reports like these are very much appreciated!
